[package]
name = "media_converter"
version = "0.1.0"
edition = '2024'

[dependencies]
actix-web = "4"
image = { version = "0.24", features = ["webp"] }
clap = { version = "4", features = ["derive"] }
chrono = "0.4.40"
httpdate = "1.0.3"
env_logger = "0.11.8"
log = "0.4.27"
